---
- name: Import role
  hosts: localhost
  gather_facts: no
  tasks:
   - name: echo
     command: echo "Hi we are going to import"
     register: output
   - name: debug
     debug:
      msg: output
   - include_role:
      name: myfirewall
#  - import_role:
#      name: git
#     when: false
